// Generated by gencpp from file tuner/GetSignalStatusRequest.msg
// DO NOT EDIT!


#ifndef TUNER_MESSAGE_GETSIGNALSTATUSREQUEST_H
#define TUNER_MESSAGE_GETSIGNALSTATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tuner
{
template <class ContainerAllocator>
struct GetSignalStatusRequest_
{
  typedef GetSignalStatusRequest_<ContainerAllocator> Type;

  GetSignalStatusRequest_()
    : channels()  {
    }
  GetSignalStatusRequest_(const ContainerAllocator& _alloc)
    : channels(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _channels_type;
  _channels_type channels;




  typedef boost::shared_ptr< ::tuner::GetSignalStatusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tuner::GetSignalStatusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSignalStatusRequest_

typedef ::tuner::GetSignalStatusRequest_<std::allocator<void> > GetSignalStatusRequest;

typedef boost::shared_ptr< ::tuner::GetSignalStatusRequest > GetSignalStatusRequestPtr;
typedef boost::shared_ptr< ::tuner::GetSignalStatusRequest const> GetSignalStatusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tuner::GetSignalStatusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tuner::GetSignalStatusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tuner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/home/attclinic/ros_catkin_ws_kinetic/install_isolated/share/nav_msgs/cmake/../msg'], 'dji_sdk': ['/home/attclinic/software/drone_ws/src/dji_sdk/msg', '/home/attclinic/software/drone_ws/devel/share/dji_sdk/msg'], 'mailroom': ['/home/attclinic/software/drone_ws/src/mailroom/msg'], 'actionlib_msgs': ['/home/attclinic/ros_catkin_ws_kinetic/install_isolated/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/home/attclinic/ros_catkin_ws_kinetic/install_isolated/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/home/attclinic/ros_catkin_ws_kinetic/install_isolated/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tuner::GetSignalStatusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuner::GetSignalStatusRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tuner::GetSignalStatusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tuner::GetSignalStatusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuner::GetSignalStatusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuner::GetSignalStatusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tuner::GetSignalStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69497818efcd0783ff3c42a6dda42dd6";
  }

  static const char* value(const ::tuner::GetSignalStatusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69497818efcd0783ULL;
  static const uint64_t static_value2 = 0xff3c42a6dda42dd6ULL;
};

template<class ContainerAllocator>
struct DataType< ::tuner::GetSignalStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tuner/GetSignalStatusRequest";
  }

  static const char* value(const ::tuner::GetSignalStatusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tuner::GetSignalStatusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[] channels\n\
";
  }

  static const char* value(const ::tuner::GetSignalStatusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tuner::GetSignalStatusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.channels);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetSignalStatusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tuner::GetSignalStatusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tuner::GetSignalStatusRequest_<ContainerAllocator>& v)
  {
    s << indent << "channels[]" << std::endl;
    for (size_t i = 0; i < v.channels.size(); ++i)
    {
      s << indent << "  channels[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.channels[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUNER_MESSAGE_GETSIGNALSTATUSREQUEST_H
