// Generated by gencpp from file mailroom/drone_telemetry.msg
// DO NOT EDIT!


#ifndef MAILROOM_MESSAGE_DRONE_TELEMETRY_H
#define MAILROOM_MESSAGE_DRONE_TELEMETRY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mailroom
{
template <class ContainerAllocator>
struct drone_telemetry_
{
  typedef drone_telemetry_<ContainerAllocator> Type;

  drone_telemetry_()
    : local_x(0.0)
    , local_y(0.0)
    , height(0)
    , az_angle(0)  {
    }
  drone_telemetry_(const ContainerAllocator& _alloc)
    : local_x(0.0)
    , local_y(0.0)
    , height(0)
    , az_angle(0)  {
  (void)_alloc;
    }



   typedef double _local_x_type;
  _local_x_type local_x;

   typedef double _local_y_type;
  _local_y_type local_y;

   typedef uint8_t _height_type;
  _height_type height;

   typedef uint8_t _az_angle_type;
  _az_angle_type az_angle;




  typedef boost::shared_ptr< ::mailroom::drone_telemetry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mailroom::drone_telemetry_<ContainerAllocator> const> ConstPtr;

}; // struct drone_telemetry_

typedef ::mailroom::drone_telemetry_<std::allocator<void> > drone_telemetry;

typedef boost::shared_ptr< ::mailroom::drone_telemetry > drone_telemetryPtr;
typedef boost::shared_ptr< ::mailroom::drone_telemetry const> drone_telemetryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mailroom::drone_telemetry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mailroom::drone_telemetry_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mailroom

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/home/attclinic/ros_catkin_ws_kinetic/install_isolated/share/nav_msgs/cmake/../msg'], 'dji_sdk': ['/home/attclinic/software/drone_ws/src/dji_sdk/msg', '/home/attclinic/software/drone_ws/devel/share/dji_sdk/msg'], 'mailroom': ['/home/attclinic/software/drone_ws/src/mailroom/msg'], 'actionlib_msgs': ['/home/attclinic/ros_catkin_ws_kinetic/install_isolated/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/home/attclinic/ros_catkin_ws_kinetic/install_isolated/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/home/attclinic/ros_catkin_ws_kinetic/install_isolated/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mailroom::drone_telemetry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mailroom::drone_telemetry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mailroom::drone_telemetry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mailroom::drone_telemetry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mailroom::drone_telemetry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mailroom::drone_telemetry_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mailroom::drone_telemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "792f8e5647216f2868c34781b5225bcb";
  }

  static const char* value(const ::mailroom::drone_telemetry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x792f8e5647216f28ULL;
  static const uint64_t static_value2 = 0x68c34781b5225bcbULL;
};

template<class ContainerAllocator>
struct DataType< ::mailroom::drone_telemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mailroom/drone_telemetry";
  }

  static const char* value(const ::mailroom::drone_telemetry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mailroom::drone_telemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 local_x\n\
float64 local_y\n\
uint8 height\n\
uint8 az_angle\n\
";
  }

  static const char* value(const ::mailroom::drone_telemetry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mailroom::drone_telemetry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.local_x);
      stream.next(m.local_y);
      stream.next(m.height);
      stream.next(m.az_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct drone_telemetry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mailroom::drone_telemetry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mailroom::drone_telemetry_<ContainerAllocator>& v)
  {
    s << indent << "local_x: ";
    Printer<double>::stream(s, indent + "  ", v.local_x);
    s << indent << "local_y: ";
    Printer<double>::stream(s, indent + "  ", v.local_y);
    s << indent << "height: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.height);
    s << indent << "az_angle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.az_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAILROOM_MESSAGE_DRONE_TELEMETRY_H
