// Generated by gencpp from file mailroom/drone_cmd.msg
// DO NOT EDIT!


#ifndef MAILROOM_MESSAGE_DRONE_CMD_H
#define MAILROOM_MESSAGE_DRONE_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mailroom/drone_telemetry.h>

namespace mailroom
{
template <class ContainerAllocator>
struct drone_cmd_
{
  typedef drone_cmd_<ContainerAllocator> Type;

  drone_cmd_()
    : telemetry()
    , channels()  {
    }
  drone_cmd_(const ContainerAllocator& _alloc)
    : telemetry(_alloc)
    , channels(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mailroom::drone_telemetry_<ContainerAllocator>  _telemetry_type;
  _telemetry_type telemetry;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _channels_type;
  _channels_type channels;




  typedef boost::shared_ptr< ::mailroom::drone_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mailroom::drone_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct drone_cmd_

typedef ::mailroom::drone_cmd_<std::allocator<void> > drone_cmd;

typedef boost::shared_ptr< ::mailroom::drone_cmd > drone_cmdPtr;
typedef boost::shared_ptr< ::mailroom::drone_cmd const> drone_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mailroom::drone_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mailroom::drone_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mailroom

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mailroom': ['/home/attclinic/software/drone_ws/src/mailroom/msg'], 'std_msgs': ['/home/attclinic/ros_catkin_ws_kinetic/install_isolated/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mailroom::drone_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mailroom::drone_cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mailroom::drone_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mailroom::drone_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mailroom::drone_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mailroom::drone_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mailroom::drone_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31c966da147198d7cc374657df64a44b";
  }

  static const char* value(const ::mailroom::drone_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31c966da147198d7ULL;
  static const uint64_t static_value2 = 0xcc374657df64a44bULL;
};

template<class ContainerAllocator>
struct DataType< ::mailroom::drone_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mailroom/drone_cmd";
  }

  static const char* value(const ::mailroom::drone_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mailroom::drone_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mailroom/drone_telemetry telemetry\n\
uint8[] channels\n\
\n\
================================================================================\n\
MSG: mailroom/drone_telemetry\n\
float64 longitude\n\
float64 latitude\n\
uint8 height\n\
uint8 az_angle\n\
";
  }

  static const char* value(const ::mailroom::drone_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mailroom::drone_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.telemetry);
      stream.next(m.channels);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct drone_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mailroom::drone_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mailroom::drone_cmd_<ContainerAllocator>& v)
  {
    s << indent << "telemetry: ";
    s << std::endl;
    Printer< ::mailroom::drone_telemetry_<ContainerAllocator> >::stream(s, indent + "  ", v.telemetry);
    s << indent << "channels[]" << std::endl;
    for (size_t i = 0; i < v.channels.size(); ++i)
    {
      s << indent << "  channels[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.channels[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAILROOM_MESSAGE_DRONE_CMD_H
