// Generated by gencpp from file mailroom/drone_cmd.msg
// DO NOT EDIT!


#ifndef MAILROOM_MESSAGE_DRONE_CMD_H
#define MAILROOM_MESSAGE_DRONE_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mailroom
{
template <class ContainerAllocator>
struct drone_cmd_
{
  typedef drone_cmd_<ContainerAllocator> Type;

  drone_cmd_()
    : data()
    , local_x(0.0)
    , local_y(0.0)
    , heights()
    , az_angle(0)
    , channels()  {
    }
  drone_cmd_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , local_x(0.0)
    , local_y(0.0)
    , heights(_alloc)
    , az_angle(0)
    , channels(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;

   typedef double _local_x_type;
  _local_x_type local_x;

   typedef double _local_y_type;
  _local_y_type local_y;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _heights_type;
  _heights_type heights;

   typedef uint8_t _az_angle_type;
  _az_angle_type az_angle;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _channels_type;
  _channels_type channels;




  typedef boost::shared_ptr< ::mailroom::drone_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mailroom::drone_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct drone_cmd_

typedef ::mailroom::drone_cmd_<std::allocator<void> > drone_cmd;

typedef boost::shared_ptr< ::mailroom::drone_cmd > drone_cmdPtr;
typedef boost::shared_ptr< ::mailroom::drone_cmd const> drone_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mailroom::drone_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mailroom::drone_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mailroom

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mailroom': ['/home/attclinic/software/drone_ws/src/mailroom/msg'], 'std_msgs': ['/home/attclinic/ros_catkin_ws_kinetic/install_isolated/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mailroom::drone_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mailroom::drone_cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mailroom::drone_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mailroom::drone_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mailroom::drone_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mailroom::drone_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mailroom::drone_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b2b47fd3d9aeb75628a01f6c100e808";
  }

  static const char* value(const ::mailroom::drone_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b2b47fd3d9aeb75ULL;
  static const uint64_t static_value2 = 0x628a01f6c100e808ULL;
};

template<class ContainerAllocator>
struct DataType< ::mailroom::drone_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mailroom/drone_cmd";
  }

  static const char* value(const ::mailroom::drone_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mailroom::drone_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data\n\
float64 local_x\n\
float64 local_y\n\
uint8[] heights\n\
uint8 az_angle\n\
uint8[] channels\n\
";
  }

  static const char* value(const ::mailroom::drone_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mailroom::drone_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.local_x);
      stream.next(m.local_y);
      stream.next(m.heights);
      stream.next(m.az_angle);
      stream.next(m.channels);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct drone_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mailroom::drone_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mailroom::drone_cmd_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
    s << indent << "local_x: ";
    Printer<double>::stream(s, indent + "  ", v.local_x);
    s << indent << "local_y: ";
    Printer<double>::stream(s, indent + "  ", v.local_y);
    s << indent << "heights[]" << std::endl;
    for (size_t i = 0; i < v.heights.size(); ++i)
    {
      s << indent << "  heights[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.heights[i]);
    }
    s << indent << "az_angle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.az_angle);
    s << indent << "channels[]" << std::endl;
    for (size_t i = 0; i < v.channels.size(); ++i)
    {
      s << indent << "  channels[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.channels[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAILROOM_MESSAGE_DRONE_CMD_H
