// Generated by gencpp from file mailroom/drone_status.msg
// DO NOT EDIT!


#ifndef MAILROOM_MESSAGE_DRONE_STATUS_H
#define MAILROOM_MESSAGE_DRONE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mailroom/drone_telemetry.h>
#include <mailroom/ATSCsignal.h>

namespace mailroom
{
template <class ContainerAllocator>
struct drone_status_
{
  typedef drone_status_<ContainerAllocator> Type;

  drone_status_()
    : telemetry()
    , signal()  {
    }
  drone_status_(const ContainerAllocator& _alloc)
    : telemetry(_alloc)
    , signal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mailroom::drone_telemetry_<ContainerAllocator>  _telemetry_type;
  _telemetry_type telemetry;

   typedef std::vector< ::mailroom::ATSCsignal_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mailroom::ATSCsignal_<ContainerAllocator> >::other >  _signal_type;
  _signal_type signal;




  typedef boost::shared_ptr< ::mailroom::drone_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mailroom::drone_status_<ContainerAllocator> const> ConstPtr;

}; // struct drone_status_

typedef ::mailroom::drone_status_<std::allocator<void> > drone_status;

typedef boost::shared_ptr< ::mailroom::drone_status > drone_statusPtr;
typedef boost::shared_ptr< ::mailroom::drone_status const> drone_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mailroom::drone_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mailroom::drone_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mailroom

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'mailroom': ['/home/attclinic/software/drone_ws/src/mailroom/msg'], 'std_msgs': ['/home/attclinic/ros_catkin_ws_kinetic/install_isolated/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mailroom::drone_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mailroom::drone_status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mailroom::drone_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mailroom::drone_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mailroom::drone_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mailroom::drone_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mailroom::drone_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b484c2ff6abc5985d5ae3dd8f029ac81";
  }

  static const char* value(const ::mailroom::drone_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb484c2ff6abc5985ULL;
  static const uint64_t static_value2 = 0xd5ae3dd8f029ac81ULL;
};

template<class ContainerAllocator>
struct DataType< ::mailroom::drone_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mailroom/drone_status";
  }

  static const char* value(const ::mailroom::drone_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mailroom::drone_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mailroom/drone_telemetry telemetry\n\
mailroom/ATSCsignal[] signal\n\
\n\
================================================================================\n\
MSG: mailroom/drone_telemetry\n\
float64 longitude\n\
float64 latitude\n\
uint8 height\n\
uint8 az_angle\n\
\n\
================================================================================\n\
MSG: mailroom/ATSCsignal\n\
uint8 channel\n\
uint8 SS\n\
uint8 SNQ\n\
";
  }

  static const char* value(const ::mailroom::drone_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mailroom::drone_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.telemetry);
      stream.next(m.signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct drone_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mailroom::drone_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mailroom::drone_status_<ContainerAllocator>& v)
  {
    s << indent << "telemetry: ";
    s << std::endl;
    Printer< ::mailroom::drone_telemetry_<ContainerAllocator> >::stream(s, indent + "  ", v.telemetry);
    s << indent << "signal[]" << std::endl;
    for (size_t i = 0; i < v.signal.size(); ++i)
    {
      s << indent << "  signal[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mailroom::ATSCsignal_<ContainerAllocator> >::stream(s, indent + "    ", v.signal[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAILROOM_MESSAGE_DRONE_STATUS_H
