// Generated by gencpp from file wheredoigo/ATSCsignal.msg
// DO NOT EDIT!


#ifndef WHEREDOIGO_MESSAGE_ATSCSIGNAL_H
#define WHEREDOIGO_MESSAGE_ATSCSIGNAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheredoigo
{
template <class ContainerAllocator>
struct ATSCsignal_
{
  typedef ATSCsignal_<ContainerAllocator> Type;

  ATSCsignal_()
    : channel()
    , SS()
    , SNQ()  {
    }
  ATSCsignal_(const ContainerAllocator& _alloc)
    : channel(_alloc)
    , SS(_alloc)
    , SNQ(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _channel_type;
  _channel_type channel;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _SS_type;
  _SS_type SS;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _SNQ_type;
  _SNQ_type SNQ;




  typedef boost::shared_ptr< ::wheredoigo::ATSCsignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheredoigo::ATSCsignal_<ContainerAllocator> const> ConstPtr;

}; // struct ATSCsignal_

typedef ::wheredoigo::ATSCsignal_<std::allocator<void> > ATSCsignal;

typedef boost::shared_ptr< ::wheredoigo::ATSCsignal > ATSCsignalPtr;
typedef boost::shared_ptr< ::wheredoigo::ATSCsignal const> ATSCsignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheredoigo::ATSCsignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheredoigo::ATSCsignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheredoigo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'wheredoigo': ['/home/attclinic/software/drone_ws/src/wheredoigo/msg'], 'std_msgs': ['/home/attclinic/ros_catkin_ws_kinetic/install_isolated/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheredoigo::ATSCsignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheredoigo::ATSCsignal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheredoigo::ATSCsignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheredoigo::ATSCsignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheredoigo::ATSCsignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheredoigo::ATSCsignal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheredoigo::ATSCsignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ccd2ea36ff16d36a5ac9c2f8d4f7377";
  }

  static const char* value(const ::wheredoigo::ATSCsignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ccd2ea36ff16d36ULL;
  static const uint64_t static_value2 = 0xa5ac9c2f8d4f7377ULL;
};

template<class ContainerAllocator>
struct DataType< ::wheredoigo::ATSCsignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheredoigo/ATSCsignal";
  }

  static const char* value(const ::wheredoigo::ATSCsignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheredoigo::ATSCsignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[] channel\n\
uint32[] SS\n\
uint32[] SNQ\n\
";
  }

  static const char* value(const ::wheredoigo::ATSCsignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheredoigo::ATSCsignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.channel);
      stream.next(m.SS);
      stream.next(m.SNQ);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ATSCsignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheredoigo::ATSCsignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheredoigo::ATSCsignal_<ContainerAllocator>& v)
  {
    s << indent << "channel[]" << std::endl;
    for (size_t i = 0; i < v.channel.size(); ++i)
    {
      s << indent << "  channel[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.channel[i]);
    }
    s << indent << "SS[]" << std::endl;
    for (size_t i = 0; i < v.SS.size(); ++i)
    {
      s << indent << "  SS[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.SS[i]);
    }
    s << indent << "SNQ[]" << std::endl;
    for (size_t i = 0; i < v.SNQ.size(); ++i)
    {
      s << indent << "  SNQ[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.SNQ[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEREDOIGO_MESSAGE_ATSCSIGNAL_H
