// Generated by gencpp from file wheredoigo/drone_cmd.msg
// DO NOT EDIT!


#ifndef WHEREDOIGO_MESSAGE_DRONE_CMD_H
#define WHEREDOIGO_MESSAGE_DRONE_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wheredoigo
{
template <class ContainerAllocator>
struct drone_cmd_
{
  typedef drone_cmd_<ContainerAllocator> Type;

  drone_cmd_()
    : data(0)
    , heights()
    , channels()  {
    }
  drone_cmd_(const ContainerAllocator& _alloc)
    : data(0)
    , heights(_alloc)
    , channels(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _data_type;
  _data_type data;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _heights_type;
  _heights_type heights;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _channels_type;
  _channels_type channels;




  typedef boost::shared_ptr< ::wheredoigo::drone_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wheredoigo::drone_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct drone_cmd_

typedef ::wheredoigo::drone_cmd_<std::allocator<void> > drone_cmd;

typedef boost::shared_ptr< ::wheredoigo::drone_cmd > drone_cmdPtr;
typedef boost::shared_ptr< ::wheredoigo::drone_cmd const> drone_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wheredoigo::drone_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wheredoigo::drone_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wheredoigo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'wheredoigo': ['/home/attclinic/software/drone_ws/src/wheredoigo/msg'], 'std_msgs': ['/home/attclinic/ros_catkin_ws_kinetic/install_isolated/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wheredoigo::drone_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wheredoigo::drone_cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheredoigo::drone_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wheredoigo::drone_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheredoigo::drone_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wheredoigo::drone_cmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wheredoigo::drone_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "356e76f7e1df41ac5081a94634ddddce";
  }

  static const char* value(const ::wheredoigo::drone_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x356e76f7e1df41acULL;
  static const uint64_t static_value2 = 0x5081a94634ddddceULL;
};

template<class ContainerAllocator>
struct DataType< ::wheredoigo::drone_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wheredoigo/drone_cmd";
  }

  static const char* value(const ::wheredoigo::drone_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wheredoigo::drone_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 data\n\
uint32[] heights\n\
uint32[] channels\n\
";
  }

  static const char* value(const ::wheredoigo::drone_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wheredoigo::drone_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.heights);
      stream.next(m.channels);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct drone_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wheredoigo::drone_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wheredoigo::drone_cmd_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.data);
    s << indent << "heights[]" << std::endl;
    for (size_t i = 0; i < v.heights.size(); ++i)
    {
      s << indent << "  heights[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.heights[i]);
    }
    s << indent << "channels[]" << std::endl;
    for (size_t i = 0; i < v.channels.size(); ++i)
    {
      s << indent << "  channels[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.channels[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHEREDOIGO_MESSAGE_DRONE_CMD_H
