# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mailroom/drone_status.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import mailroom.msg

class drone_status(genpy.Message):
  _md5sum = "b484c2ff6abc5985d5ae3dd8f029ac81"
  _type = "mailroom/drone_status"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """mailroom/drone_telemetry telemetry
mailroom/ATSCsignal[] signal

================================================================================
MSG: mailroom/drone_telemetry
float64 longitude
float64 latitude
uint8 height
uint8 az_angle

================================================================================
MSG: mailroom/ATSCsignal
uint8 channel
uint8 SS
uint8 SNQ
"""
  __slots__ = ['telemetry','signal']
  _slot_types = ['mailroom/drone_telemetry','mailroom/ATSCsignal[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       telemetry,signal

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(drone_status, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.telemetry is None:
        self.telemetry = mailroom.msg.drone_telemetry()
      if self.signal is None:
        self.signal = []
    else:
      self.telemetry = mailroom.msg.drone_telemetry()
      self.signal = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2d2B().pack(_x.telemetry.longitude, _x.telemetry.latitude, _x.telemetry.height, _x.telemetry.az_angle))
      length = len(self.signal)
      buff.write(_struct_I.pack(length))
      for val1 in self.signal:
        _x = val1
        buff.write(_get_struct_3B().pack(_x.channel, _x.SS, _x.SNQ))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.telemetry is None:
        self.telemetry = mailroom.msg.drone_telemetry()
      if self.signal is None:
        self.signal = None
      end = 0
      _x = self
      start = end
      end += 18
      (_x.telemetry.longitude, _x.telemetry.latitude, _x.telemetry.height, _x.telemetry.az_angle,) = _get_struct_2d2B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.signal = []
      for i in range(0, length):
        val1 = mailroom.msg.ATSCsignal()
        _x = val1
        start = end
        end += 3
        (_x.channel, _x.SS, _x.SNQ,) = _get_struct_3B().unpack(str[start:end])
        self.signal.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2d2B().pack(_x.telemetry.longitude, _x.telemetry.latitude, _x.telemetry.height, _x.telemetry.az_angle))
      length = len(self.signal)
      buff.write(_struct_I.pack(length))
      for val1 in self.signal:
        _x = val1
        buff.write(_get_struct_3B().pack(_x.channel, _x.SS, _x.SNQ))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.telemetry is None:
        self.telemetry = mailroom.msg.drone_telemetry()
      if self.signal is None:
        self.signal = None
      end = 0
      _x = self
      start = end
      end += 18
      (_x.telemetry.longitude, _x.telemetry.latitude, _x.telemetry.height, _x.telemetry.az_angle,) = _get_struct_2d2B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.signal = []
      for i in range(0, length):
        val1 = mailroom.msg.ATSCsignal()
        _x = val1
        start = end
        end += 3
        (_x.channel, _x.SS, _x.SNQ,) = _get_struct_3B().unpack(str[start:end])
        self.signal.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
_struct_2d2B = None
def _get_struct_2d2B():
    global _struct_2d2B
    if _struct_2d2B is None:
        _struct_2d2B = struct.Struct("<2d2B")
    return _struct_2d2B
