// Auto-generated. Do not edit!

// (in-package dji_sdk.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class DroneTaskGoal {
  constructor() {
    this.task = 0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type DroneTaskGoal
    // Serialize message field [task]
    bufferInfo = _serializer.uint8(obj.task, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type DroneTaskGoal
    let tmp;
    let len;
    let data = new DroneTaskGoal();
    // Deserialize message field [task]
    tmp = _deserializer.uint8(buffer);
    data.task = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'dji_sdk/DroneTaskGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'cfae433ef22bd8313f92bc5cad00c264';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    uint8 task 
    
    `;
  }

};

module.exports = DroneTaskGoal;
