// Auto-generated. Do not edit!

// (in-package dji_sdk.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class DroneTaskFeedback {
  constructor() {
    this.progress = 0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type DroneTaskFeedback
    // Serialize message field [progress]
    bufferInfo = _serializer.uint8(obj.progress, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type DroneTaskFeedback
    let tmp;
    let len;
    let data = new DroneTaskFeedback();
    // Deserialize message field [progress]
    tmp = _deserializer.uint8(buffer);
    data.progress = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'dji_sdk/DroneTaskFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd0ccee79f15d1d61b42a87d5f604edbc';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    uint8 progress 
    
    
    `;
  }

};

module.exports = DroneTaskFeedback;
