// Auto-generated. Do not edit!

// (in-package dji_sdk.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class GlobalPositionNavigationFeedback {
  constructor() {
    this.latitude_progress = 0;
    this.longitude_progress = 0;
    this.altitude_progress = 0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type GlobalPositionNavigationFeedback
    // Serialize message field [latitude_progress]
    bufferInfo = _serializer.uint8(obj.latitude_progress, bufferInfo);
    // Serialize message field [longitude_progress]
    bufferInfo = _serializer.uint8(obj.longitude_progress, bufferInfo);
    // Serialize message field [altitude_progress]
    bufferInfo = _serializer.uint8(obj.altitude_progress, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type GlobalPositionNavigationFeedback
    let tmp;
    let len;
    let data = new GlobalPositionNavigationFeedback();
    // Deserialize message field [latitude_progress]
    tmp = _deserializer.uint8(buffer);
    data.latitude_progress = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [longitude_progress]
    tmp = _deserializer.uint8(buffer);
    data.longitude_progress = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [altitude_progress]
    tmp = _deserializer.uint8(buffer);
    data.altitude_progress = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'dji_sdk/GlobalPositionNavigationFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '799b45a00bba65b59dcde12d51bf8bba';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #progress is in percent
    uint8 latitude_progress
    uint8 longitude_progress
    uint8 altitude_progress
    
    
    `;
  }

};

module.exports = GlobalPositionNavigationFeedback;
