// Auto-generated. Do not edit!

// (in-package dji_sdk.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');
let GlobalPositionNavigationActionGoal = require('./GlobalPositionNavigationActionGoal.js');
let GlobalPositionNavigationActionResult = require('./GlobalPositionNavigationActionResult.js');
let GlobalPositionNavigationActionFeedback = require('./GlobalPositionNavigationActionFeedback.js');

//-----------------------------------------------------------

class GlobalPositionNavigationAction {
  constructor() {
    this.action_goal = new GlobalPositionNavigationActionGoal();
    this.action_result = new GlobalPositionNavigationActionResult();
    this.action_feedback = new GlobalPositionNavigationActionFeedback();
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type GlobalPositionNavigationAction
    // Serialize message field [action_goal]
    bufferInfo = GlobalPositionNavigationActionGoal.serialize(obj.action_goal, bufferInfo);
    // Serialize message field [action_result]
    bufferInfo = GlobalPositionNavigationActionResult.serialize(obj.action_result, bufferInfo);
    // Serialize message field [action_feedback]
    bufferInfo = GlobalPositionNavigationActionFeedback.serialize(obj.action_feedback, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type GlobalPositionNavigationAction
    let tmp;
    let len;
    let data = new GlobalPositionNavigationAction();
    // Deserialize message field [action_goal]
    tmp = GlobalPositionNavigationActionGoal.deserialize(buffer);
    data.action_goal = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [action_result]
    tmp = GlobalPositionNavigationActionResult.deserialize(buffer);
    data.action_result = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [action_feedback]
    tmp = GlobalPositionNavigationActionFeedback.deserialize(buffer);
    data.action_feedback = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'dji_sdk/GlobalPositionNavigationAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '8a12457fcfde38a41ea6db6ebec5f2f1';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    GlobalPositionNavigationActionGoal action_goal
    GlobalPositionNavigationActionResult action_result
    GlobalPositionNavigationActionFeedback action_feedback
    
    ================================================================================
    MSG: dji_sdk/GlobalPositionNavigationActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    GlobalPositionNavigationGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: dji_sdk/GlobalPositionNavigationGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #latitude is in degree
    float64 latitude
    #longitude is in degree
    float64 longitude
    float32 altitude
    
    ================================================================================
    MSG: dji_sdk/GlobalPositionNavigationActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    GlobalPositionNavigationResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: dji_sdk/GlobalPositionNavigationResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    bool result
    
    ================================================================================
    MSG: dji_sdk/GlobalPositionNavigationActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    GlobalPositionNavigationFeedback feedback
    
    ================================================================================
    MSG: dji_sdk/GlobalPositionNavigationFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #progress is in percent
    uint8 latitude_progress
    uint8 longitude_progress
    uint8 altitude_progress
    
    
    `;
  }

};

module.exports = GlobalPositionNavigationAction;
