// Auto-generated. Do not edit!

// (in-package dji_sdk.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');

//-----------------------------------------------------------

class LocalPositionNavigationFeedback {
  constructor() {
    this.x_progress = 0;
    this.y_progress = 0;
    this.z_progress = 0;
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type LocalPositionNavigationFeedback
    // Serialize message field [x_progress]
    bufferInfo = _serializer.uint8(obj.x_progress, bufferInfo);
    // Serialize message field [y_progress]
    bufferInfo = _serializer.uint8(obj.y_progress, bufferInfo);
    // Serialize message field [z_progress]
    bufferInfo = _serializer.uint8(obj.z_progress, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type LocalPositionNavigationFeedback
    let tmp;
    let len;
    let data = new LocalPositionNavigationFeedback();
    // Deserialize message field [x_progress]
    tmp = _deserializer.uint8(buffer);
    data.x_progress = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [y_progress]
    tmp = _deserializer.uint8(buffer);
    data.y_progress = tmp.data;
    buffer = tmp.buffer;
    // Deserialize message field [z_progress]
    tmp = _deserializer.uint8(buffer);
    data.z_progress = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'dji_sdk/LocalPositionNavigationFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'dc1f44f25fca6f00e17022e1b8cc9f3e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #progress is in percent
    uint8 x_progress 
    uint8 y_progress 
    uint8 z_progress 
    
    
    `;
  }

};

module.exports = LocalPositionNavigationFeedback;
