// Auto-generated. Do not edit!

// (in-package dji_sdk.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');
let WaypointList = require('./WaypointList.js');

//-----------------------------------------------------------

class WaypointNavigationGoal {
  constructor() {
    this.waypoint_list = new WaypointList();
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type WaypointNavigationGoal
    // Serialize message field [waypoint_list]
    bufferInfo = WaypointList.serialize(obj.waypoint_list, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type WaypointNavigationGoal
    let tmp;
    let len;
    let data = new WaypointNavigationGoal();
    // Deserialize message field [waypoint_list]
    tmp = WaypointList.deserialize(buffer);
    data.waypoint_list = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'dji_sdk/WaypointNavigationGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'f8c17a2713443e9792d80cdae0b731c2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    WaypointList waypoint_list
    
    ================================================================================
    MSG: dji_sdk/WaypointList
    Waypoint[] waypoint_list
    
    ================================================================================
    MSG: dji_sdk/Waypoint
    #latitude is in degree
    float64 latitude
    #longitude is in degree
    float64 longitude
    float32 altitude
    #heading is in [-180,180]
    int16 heading 
    #stay time is in second
    uint16 staytime
    
    `;
  }

};

module.exports = WaypointNavigationGoal;
